### ISSUE TITLE
call不能转递json嘛

### ISSUE THREAD

**Issue by 903531306** [woyehaizaixiang/DsBridge#1]
我在传递json转为string 传递的时候会报错
"Uncaught SyntaxError: missing ) after argument list",

**Comment by woyehaizaixiang** [comment]
> 我在传递json转为string 传递的时候会报错 "Uncaught SyntaxError: missing ) after argument list",

方便截一段代码看下

**Comment by 903531306** [comment]
箭头1转为json&nbsp; 箭头2json的内容&nbsp; 箭头3传递



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月12日(星期四) 晚上8:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1)





  
我在传递json转为string 传递的时候会报错 "Uncaught SyntaxError: missing ) after argument list",
  
方便截一段代码看下

**Comment by woyehaizaixiang** [comment]
> 箭头1转为json&nbsp; 箭头2json的内容&nbsp; 箭头3传递
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年5月12日(星期四) 晚上8:31 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1) 我在传递json转为string 传递的时候会报错 "Uncaught SyntaxError: missing ) after argument list", 方便截一段代码看下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

网页端掉用请参考这里的文档https://github.com/woyehaizaixiang/dsbridge_flutter

**Comment by 903531306** [comment]
那意思 我这样是可以传递的是吧&nbsp; 就是网页端有问题是么




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月12日(星期四) 晚上8:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1)





  
箭头1转为json&nbsp; 箭头2json的内容&nbsp; 箭头3传递
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年5月12日(星期四) 晚上8:31 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1) 我在传递json转为string 传递的时候会报错 "Uncaught SyntaxError: missing ) after argument list", 方便截一段代码看下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
网页端掉用请参考这里的文档https://github.com/woyehaizaixiang/dsbridge_flutter

**Comment by woyehaizaixiang** [comment]
> 那意思 我这样是可以传递的是吧&nbsp; 就是网页端有问题是么
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年5月12日(星期四) 晚上8:42 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1) 箭头1转为json&nbsp; 箭头2json的内容&nbsp; 箭头3传递 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年5月12日(星期四) 晚上8:31 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1) 我在传递json转为string 传递的时候会报错 "Uncaught SyntaxError: missing ) after argument list", 方便截一段代码看下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 网页端掉用请参考这里的文档https://github.com/woyehaizaixiang/dsbridge_flutter — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我不明白你说的是哪里报错？

**Comment by 903531306** [comment]
只要传递json&nbsp; 就会报这个错误 Json转string






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月12日(星期四) 晚上8:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1)





  
那意思 我这样是可以传递的是吧&nbsp; 就是网页端有问题是么
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年5月12日(星期四) 晚上8:42 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1) 箭头1转为json&nbsp; 箭头2json的内容&nbsp; 箭头3传递 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年5月12日(星期四) 晚上8:31 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1) 我在传递json转为string 传递的时候会报错 "Uncaught SyntaxError: missing ) after argument list", 方便截一段代码看下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 网页端掉用请参考这里的文档https://github.com/woyehaizaixiang/dsbridge_flutter — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
我不明白你说的是哪里报错？

**Comment by woyehaizaixiang** [comment]
> 

网页端dsBridge.call的时候入参不能为json，建议参考文档例子

**Comment by woyehaizaixiang** [comment]
> 只要传递json&nbsp; 就会报这个错误 Json转string
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年5月12日(星期四) 晚上8:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1) 那意思 我这样是可以传递的是吧&nbsp; 就是网页端有问题是么 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年5月12日(星期四) 晚上8:42 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1) 箭头1转为json&nbsp; 箭头2json的内容&nbsp; 箭头3传递 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年5月12日(星期四) 晚上8:31 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1) 我在传递json转为string 传递的时候会报错 "Uncaught SyntaxError: missing ) after argument list", 方便截一段代码看下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 网页端掉用请参考这里的文档https://github.com/woyehaizaixiang/dsbridge_flutter — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 我不明白你说的是哪里报错？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

网页端dsBridge.call的时候入参不能为json，建议参考文档例子

**Comment by 903531306** [comment]
能否加个联系方式聊下 我确实也是按照文档的处理的&nbsp; 但是遇到了问题！帮忙解决下 有偿&nbsp;QQ903531306



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月12日(星期四) 晚上9:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [woyehaizaixiang/DsBridge] call不能转递json嘛 (Issue #1)





   
网页端dsBridge.call的时候入参不能为json，建议参考文档例子

**Comment by woyehaizaixiang** [comment]
已优化于ds_bridge: ^0.0.2
